spring:

  name: "kafka-elastic-connect"

  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092
    topic: "in"
  data:
    elasticsearch:
      index: "index-name"
      cluster-nodes: "localhost:9300"
      cluster-name: "docker-cluster"